### ISSUE TITLE
one of .git/objects/pack is too large as it contains a binary in it

### ISSUE THREAD

**Issue by wonderflow** [crossplane/addon-oam-kubernetes-local#14]
![image](https://user-images.githubusercontent.com/2173670/79677830-c34a8e00-8227-11ea-824a-470b0b849fdf.png)

Maybe we need to clean it up as the project is still at initial time.

**Comment by wonderflow** [comment]
Maybe we also need to change the repo name together with this change.

What about `oam-addon-default`

**Comment by ryanzhang-oss** [comment]
done (not the repro part)

**Comment by wonderflow** [comment]
cool，thanks
