### ISSUE TITLE
Set up core/standard/extention trait/workload structure in the repro

### ISSUE THREAD

**Issue by ryanzhang-oss** [crossplane/addon-oam-kubernetes-local#19]
We have community members that want to contribute to our OAM workload/trait system. We need to define the structure of this repro to accommodate future needs.  The ideal situation is that we can have multiple controllers that can be built to individual docker images.

**Comment by ryanzhang-oss** [comment]
The current plan is to move those community OAM resources to another place

**Comment by wonderflow** [comment]
I've setup a repo here: https://github.com/oam-dev/catalog
