### ISSUE TITLE
Error installing helm charts

### ISSUE THREAD

**Issue by artursouza** [crossplane/addon-oam-kubernetes-local#20]
[21:56:13] ~/Code/crossplane/addon-oam-kubernetes-local (master)
$ helm install controller -n oam-system ./charts/oam-core-resources/
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"]

**Comment by ryanzhang-oss** [comment]
https://github.com/oam-dev/samples/pull/33

**Comment by artursouza** [comment]
Repro steps:
* Kubernetes 1.15 on Docker Desktop.
* Helm 3
* Reset Kubernetes cluster on Docker Desktop settings.
 * Replay steps as per: https://github.com/crossplane/addon-oam-kubernetes-local

**Comment by wonderflow** [comment]
closing as it was fixed by #22
