### ISSUE TITLE
Improvement needed in README

### ISSUE THREAD

**Issue by resouer** [crossplane/addon-oam-kubernetes-local#3]
1. Need a  prerequisites section, including:
```
go version xxx
Kubernetes version v1.15+ (because `cert-manager` CRD has `preserveUnknownFields`).
helm 3.1+ (`helm install --devel` requires this)
kubebuilder must be installed (`make docker-build` assumes etcd exists under kubebuilder bin - path)
```

2. It's not encouraged to set `--validate=false`, this will hide validation issues caused by version conflicts etc.

3. These two steps are fragile:
```
make docker-build IMG=controller:v1
make deploy IMG=controller:v1
```
We need to make release and push the image to oam-dev hub with proper image tag. And the install could be one-line:
```
kubectl apply -f oam-kubernetes-controller.yaml
```

Also, even for developers of this project, we probably need to push the image to remote e.g.:

```
IMG=docker.io/ryanzhang/controller:v1
make docker-build
make deploy
```

The reason is, ppl may use [Kind](https://kind.sigs.k8s.io) and his K8s cluster is not able to access images on host by default.

**Comment by ryanzhang-oss** [comment]
https://github.com/crossplane/addon-oam-kubernetes-local/pull/4

**Comment by resouer** [comment]
Since #4 is merged, most of the TODOs in this issue are fixed, thanks!

I think the remaining one is we need to cut a release for this work and upload its Docker image and Helm charts in public hub. So no need to git clone the repo to local (this is painful).

**Comment by ryanzhang-oss** [comment]
fixed
