### ISSUE TITLE
Kubernetes 1.17 is not widely available

### ISSUE THREAD

**Issue by muvaf** [crossplane/addon-oam-kubernetes-local#30]
As stated in the README, having Kubernetes 1.17 is required. As of this writing, here is the list of available versions in big clouds:
* AWS: 1.15 default, 1.16 is max
* GCP: 1.14 default, 1.16 is max
* Azure: 1.15 default, 1.16 is max, 1.17 as preview
* Alibaba: 1.14 is mentioned in [docs](https://www.alibabacloud.com/help/doc-detail/95108.htm) but I couldn't check the console because I don't have creds.

It seems to me that it is not possible to deploy local OAM addon into a production cluster. I think it makes sense to reassess which parts require 1.17 and develop alternative solutions to make it compatible with 1.14 even with some missing features for some versions.

**Comment by negz** [comment]
It looks like the requirement for 1.17 was documented in https://github.com/crossplane/addon-oam-kubernetes-local/pull/22. That PR seems to imply that 1.15 was insufficient, but it's not clear why 1.17 was chosen. Perhaps it was just the latest at the time? CC @artursouza in case you have more context.

I suspect 1.16 will be the best compromise here. I believe this codebase uses server-side apply, which I believe was promoted from alpha to beta in 1.16.

**Comment by ryanzhang-oss** [comment]
We can turn off webhooks in the helm chart if there are other things related to admission hooks that require 1.17.   It seems that 1.16 is supported by all of the cloud providers. I have confirmed that Alibaba ACK also supports 1.16.

**Comment by artursouza** [comment]
1.15 is not enough because of the webhook mentioned above - I experienced that issue. 1.17 was the one we found to satisfy that.

**Comment by ryanzhang-oss** [comment]
> 1.15 is not enough because of the webhook mentioned above - I experienced that issue. 1.17 was the one we found to satisfy that.

The webhook is disabled by default in the local addon helm so I think you can run it on 1.16.

**Comment by artursouza** [comment]
Ok. Let me change doc to 1.16

**Comment by ryanzhang-oss** [comment]
> Ok. Let me change doc to 1.16

Thanks, can I close this issue after you verified that it works on 1.16?  I am positive that it works

**Comment by muvaf** [comment]
The webhook is disabled by default with this [PR](https://github.com/crossplane/addon-oam-kubernetes-local/pull/31). I had confirmed that installation works on 1.16 before the release.
