### ISSUE TITLE
The App bootstrapped with 10 replicas, which seems too many

### ISSUE THREAD

**Issue by resouer** [crossplane/addon-oam-kubernetes-local#5]
For instance: 

```
kubectl get deploy
NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
example-appconfig-workload-deployment   6/10    10           6           11m
```

Note that the deployment has memory limit:
```
Limits:
      memory:  200Mi
```

10x200M seems unnecessary, it exceed Kind or Minikube VM's default memory quota in many cases. 

I'd suggest we make it 3.

Also, I am not sure where the replicas 10 come from? Seems not in the chart `values.yaml`.

**Comment by ryanzhang-oss** [comment]
fixed
