### ISSUE TITLE
Workload type should not be hard coding

### ISSUE THREAD

**Issue by resouer** [crossplane/addon-oam-kubernetes-local#8]
https://github.com/crossplane/addon-oam-kubernetes-local/blob/3f7e32cc89d7d0cf9e60c9b2eeb71fa1c06730d2/controllers/manualscalertrait_controller.go#L69

Seems the workload type should be `trait.workloadRef.kind`?

**Comment by wonderflow** [comment]
:+1: another way to fix it quickly is we limit the manualScaler trait only apply to ContainerizedWorkload

**Comment by ryanzhang-oss** [comment]
https://github.com/crossplane/addon-oam-kubernetes-local/pull/26
